add_newline = true

format = "$directory$git_branch$git_status$line_break$time$character"

[character]
success_symbol = "[✨ ➜](bold green)"
error_symbol = "[💀 ➜](bold red)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "🌱 "
style = "bold yellow"

[time]
disabled = false
use_12hr = false
format = "[🕒 $time]($style) "
style = "bold purple"
