theme = "default"

[editor]
line-number = "relative"
mouse = true
cursorline = true
true-color = true
color-modes = true
bufferline = "multiple"

[editor.indent-guides]
render = true
character = "|"

[editor.file-picker]
hidden = false
